//Animals
export const UPDATE_ANIMAL = "UPDATE_ANIMAL";
export const ADD_ANIMAL = "ADD_ANIMAL";
export const SAVE_ANIMAL = "SAVE_ANIMAL";
export const DELETE_ANIMAL = "DELETE_ANIMAL";

//Prescriptions
export const UPDATE_PRESCRIPTION = "UPDATE_PRESCRIPTION";
export const ADD_PRESCRIPTION = "ADD_PRESCRIPTION";
export const SAVE_PRESCRIPTION = "SAVE_PRESCRIPTION";
export const DELETE_PRESCRIPTION = "DELETE_PRESCRIPTION";